config/routes.rb
Rails.application.routes.draw do

  root 'travellers#landing'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home' => 'travellers#landing'
  get 'travellers/dashboard' => 'travellers#index'
  get '/profilepicture' => 'travellers#profilepic'
  post '/profilepicture' => 'travellers#createpic'
  get 'travellers/findguide' => 'travellers#findguide'
  post 'travellers/create' => 'travellers#createsearch'
  get 'travellers/searchresults'=> 'travellers#persistentresults'
  get '/travellers/becomeaguide' =>  'travellers#becomeaguide', as: 'user'
  post '/travellers/becomeaguide' => 'travellers#makeguide'

  resources :travellers

  resources :guides do
    resources :experiences
    resources :reviews
  end



  resources :conversations do
    resources :messages
  end


end

app/views/shared/_dashboardheader.html.erb
<% landscape_img = ["https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80","https://images.unsplash.com/photo-1491557345352-5929e343eb89?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80","https://images.unsplash.com/photo-1516545595035-b494dd0161e4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80","https://images.unsplash.com/photo-1526662075745-edd1c71a4cff?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80","https://images.unsplash.com/photo-1539768942893-daf53e448371?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=751&q=80","https://images.unsplash.com/photo-1520681279154-51b3fb4ea0f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80"] %>


<div style="height: 60vh; background: url(<%= landscape_img[rand(6)] %>) no-repeat center center fixed; background-size: cover;"></div>


<% if current_user.avatar.attached? %>
  <div style="border: .5rem solid white; margin-right: 1rem; margin-top: -75px; width: 150px; height: 150px; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url('<%= url_for(current_user.avatar) %>')" class="ml-auto"></div>

  <% else %>

  <div style="border: .5rem solid white; margin-right: 1rem; margin-top: -75px; width: 150px; height: 150px; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url(https://live.staticflickr.com/8518/8431890328_87cc217dbe_z.jpg)" class="ml-auto"></div>
<% end %>
<div class="d-flex">
	<div class="col-auto flex-shrink-1 rounded-top p-3 ml-3" style="margin-top: -225px; background-color: rgba(255,255,255,.7);">
		<h1 class="display-4">Hello, <span class="text-secondary"><%= @user.name %></span></h1>
		<p class="lead d-flex justify-content-between pb-2"><span>Your location: <br><span class="text-secondary"><%= @user.location %></span></span><a href = '/users/edit' class="btn btn-outline-secondary btn-sm text-end m-3"><i class="fas fa-user-edit"></i></a></p>
		<% if current_page?(guides_path) %>
				<a href="/travellers" class="btn btn-outline-secondary btn-sm mb-5 ml-3">Traveller's home page</a>
		<% else %>
			<% if @user.guide %>
				<a href="/guides" class="btn btn-outline-secondary btn-sm mb-5 ml-3">Guide's dashboard</a>
			<% else %>
				<a href="/travellers/becomeaguide" class="btn btn-outline-secondary btn-sm mb-5 ml-3">Become a guide and showcase your city!</a>
			<% end %>
		<% end %>
	</div>
</div>