config/routes.rb
Rails.application.routes.draw do

  root 'travellers#landing'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home' => 'travellers#landing'
  get 'travellers/dashboard' => 'travellers#index'
  get '/profilepicture' => 'travellers#profilepic'
  post '/profilepicture' => 'travellers#createpic'
  get 'travellers/findguide' => 'travellers#findguide'
  post 'travellers/create' => 'travellers#createsearch'
  get 'travellers/searchresults'=> 'travellers#persistentresults'
  get '/travellers/becomeaguide' =>  'travellers#becomeaguide', as: 'user'
  post '/travellers/becomeaguide' => 'travellers#makeguide'

  resources :travellers

  resources :guides do
    resources :experiences
    resources :reviews
  end



  resources :conversations do
    resources :messages
  end


end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :category
  belongs_to :guide
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController

  def authenticate_guide!
    # check if current user is guide
    unless current_user.guide
      # if current_user is not guide redirect to some route
      redirect_to '/'
    end
    # if current_user is guide he will proceed to new/edit
  end

  before_action :authenticate_guide!, only: [:new, :edit]

  def index
    @experiences = Experience.all
  end

  def new
    @experience = Experience.new
    @categories = Category.all
  end

  def create
    @experience = Experience.new(experience_params)
    @categories = Category.all
    @guide = current_user.guide
    @experience.guide = @guide
    if @experience.save
      redirect_to '/guides'
    else
      render 'new'
    end
  end

  def edit
    @experience = experience.find(params[:id])
    @categories = Category.all
  end

  def update
    @experience = experience.find(params[:id])
    @experience.update(experience_params)
    redirect_to @experience
  end

  def show
    @experience = experience.find(params[:id])
  end

  def destroy
    @experience = experience.find(params[:id])
    @experience.destroy
    redirect_to @experience
  end

  private def experience_params
    params.require(:experience).permit(:title, :description, :img, :category_id)
  end
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/views/experiences/new.html.erb
<div class="container">
	<div class="row d-flex justify-content-around">

		<div class="col-8">
	  	<img class="img-fluid" src="https://images.unsplash.com/photo-1459231978203-b7d0c47a2cb7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1498&q=80">
	  </div>
		<div style="margin-left: -600px;" class="col-4 text-center bg-white my-5 rounded shadow py-4">
			<h4>Add a new experience</h4>
			<%= form_with scope: :experience, url: guide_experiences_path, local: true do |form| %>
				<div class="form-group">
			  	<%= form.collection_select(:category_id, @categories, :id, :name, {:include_blank => 'Select category...'}, {:class => "custom-select"}) %>
			  </div>

				<div class="form-group">
			    <%= form.label :title %><br>
			    <%= form.text_field :title, :class => "form-control" %>
			  </div>

			  <div class="form-group">
			    <%= form.label :description, "Description of the experience" %><br>
			    <%= form.text_area :description, :class => "form-control" %>
			  </div>

			  <div class="form-group">
			    <%= form.label :img, "Attach an image relevant to the experience" %><br>
			    <%= form.text_field :img, :class => "form-control" %>
			  </div>

			  <div class="form-group">
			    <%= form.submit({:class => "btn btn-success btn-block rounded-pill"}) %>
			  </div>
			<% end %>
		</div>
	</div>
</div>