config/routes.rb
Rails.application.routes.draw do

  root 'travellers#landing'


  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/home' => 'travellers#landing'
  get 'travellers/dashboard' => 'travellers#index'
  get '/profilepicture' => 'travellers#profilepic'
  post '/profilepicture' => 'travellers#createpic'
  get 'travellers/findguide' => 'travellers#findguide'
  post 'travellers/create' => 'travellers#createsearch'
  get 'travellers/searchresults'=> 'travellers#persistentresults'
  get '/travellers/becomeaguide' =>  'travellers#becomeaguide', as: 'user'
  post '/travellers/becomeaguide' => 'travellers#makeguide'

  resources :travellers

  resources :guides do
    resources :experiences
    resources :reviews
  end



  resources :conversations do
    resources :messages
  end


end

app/models/guide.rb
class Guide < ApplicationRecord
    has_many :experiences, dependent: :destroy
    belongs_to :user
    has_many :reviews
end

app/controllers/guides_controller.rb
class GuidesController < ApplicationController

  def index
    @user = current_user
    @guide = @user.guide
    @conversations = Conversation.all
    # @reviews = Review.all.sort_by(&:created_at).reverse

    @reviews = Review.where(guide_id: @guide.id).sort_by(&:created_at).reverse

  end

  def show
    @guide = Guide.find(params[:id])
  end

end

app/helpers/guides_helper.rb
module GuidesHelper
end

app/views/guides/index.html.erb
<div id="notifications"></div>

<%# greeting banner %>
<%= render "shared/dashboardheader", locales: {:user => @user} %>

<%# dashboard main %>
<div class="container">
	<div class="row mb-5">
		<div class="col-8">
			<p class="lead">Your bio: <span class="text-secondary"><%= @guide.bio %></span></p>

			<p class="lead">
				Your interests:
				<% interests = [] %>
				<% @guide.experiences.each do |experience| %>
					<% if !interests.include?(experience.category.name) %>
						<% interests.push(experience.category.name) %>
					<% end %>
				<% end %>
				<% interests.each do |interest| %>
					<span class="badge badge-pill badge-success"><%= interest %></span>
				<% end %>
			</p>
		</div>
		<div class="col-4 border-left">
			<p class="lead text-center">Your average rating:</p>
			<% if !@guide.reviews.empty? %>
				<p class="lead text-center">
					<% average_rating = @guide.reviews.average("rating").round(1) %>
					<span><%= average_rating %></span>
				</p>
				<p class="lead text-center text-success">
					<% average_rating.to_i.times do %>
	 					<i class="fas fa-star"></i>
					<% end %>
					<% (5-average_rating.to_i).times do %>
						<i class="far fa-star"></i>
					<% end %>
				</p>
			<% else %>
				<p class="h4 text-center text-secondary">- -</p>
			<% end %>
		</div>
	</div>
</div>

<%# visible only on xs %>
<div class="d-block d-sm-none">
	<ul class="nav nav-tabs nav-fill" id="myTab" role="tablist">
	  <li class="nav-item">
	    <a class="nav-link" id="experiences-tab" data-toggle="tab" href="#experiences" role="tab">Experiences</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link active" id="conversations-tab" data-toggle="tab" href="#conversations" role="tab">Messages</a>
	  </li>
	  <li class="nav-item">
	    <a class="nav-link" id="reviews-tab" data-toggle="tab" href="#reviews" role="tab">Reviews</a>
	  </li>
	</ul>
	<div class="tab-content mb-5" id="myTabContent">
<%# experiences tab %>
  	<div class="tab-pane fade show" id="experiences" role="tabpanel">
			<div class="accordion" id="experience_accordion">
				<% @guide.experiences.each do |experience| %>
	  			<div class="card">
	    			<div class="card-header" id="heading<%=experience.id%>">
	      			<h2 class="mb-0">
	        			<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%=experience.id%>" >
	          			<%= experience.title %>
	        			</button>
	      			</h2>
	    			</div>
	    			<div id="collapse<%=experience.id%>" class="collapse" data-parent="#experience_accordion">
	      			<div class="card-body">
	        			<%= experience.description %>
	      			</div>
	    			</div>
	  			</div>
	  		<% end %>
			</div>
			<a href="/guides/<%= @user.id %>/experiences/new" class="btn btn-block btn-success" style="border-top-right-radius: 0;border-top-left-radius: 0;">Add Experience <i class="fas fa-plus"></i></a>
		</div>
<%# conversations tab %>
	  <div class="mt-3 tab-pane fade show active" id="conversations" role="tabpanel">
	  	<% if @conversations.where(recipient_id: @guide.user).empty? %>
	  		<div class="text-center">
	  			<h4>No messages yet</h4>
	  		</div>
	  	<% else %>
		  	<% @conversations.each do |conversation| %>
	  			<% if conversation.recipient_id == current_user.id %>
	  				<% sender = User.find(conversation.sender_id) %>
	  				<div class= " d-flex justify-content-between" role="">
							<%= link_to sender.name, conversation_messages_path(conversation), :class => "text-dark"%>
						</div>
	  			<% end %>
	  		<% end %>
	  	<% end %>
	  </div>
<%# reviews tab %>
	  <div class="tab-pane fade show mt-4" id="reviews" role="tabpanel">
	  	<% if @reviews.empty? %>
	  		<div class="text-center">
	  			<h4>No reviews yet</h4>
	  		</div>
	  	<% else %>
		  	<% @reviews.each do |review|%>

		  			<div class="row mt-3 border-bottom pb-3">
	  					<div class="col-4 mt-3 text-center">
	  						<small class="lead text-center text-success">
									<% review.rating.times do %>
					 					<i class="fas fa-star"></i>
									<% end %>
									<% (5-review.rating).times do %>
										<i class="far fa-star"></i>
									<% end %>
								</small>
								<p class="mt-1">By: <strong class="text-secondary"><%= review.user.name %></strong></p>
								<small class="text-muted">On <%= review.created_at.strftime("%B %-d, %Y") %></small>
							</div>
							<div class="col-8 border rounded d-flex justify-content-center align-items-center bg-light">
								<p>"<%= review.body %>"</p>
							</div>
						</div>

				<% end %>
			<% end %>
		</div>
	</div>
</div>
<%# hidden only on xs %>
<div class="container d-none d-sm-block">
	<div class="row">
<%# conversations column %>
		<div class="col-12 mb-4">
			<div class="card px-0">
		  	<h5 class="card-header">Messages</h5>
				<div class="card-body">
					<% if @conversations.where(recipient_id: @guide.user).empty? %>
			  		<div class="text-center">
			  			<h4>No messages yet</h4>
			  		</div>
			  	<% else %>
				  	<% @conversations.each do |conversation| %>
			  			<% if conversation.recipient_id == current_user.id %>
			  				<% sender = User.find(conversation.sender_id) %>
			  				<div class="d-flex justify-content-between" role="">
									<%= link_to sender.name, conversation_messages_path(conversation), :class => "text-dark"%>
								</div>
			  			<% end %>
			  		<% end %>
			  	<% end %>
				</div>
			</div>
		</div>
<%# experiences column %>
		<div class="col-4">
			<div class="card px-0">
				<h5 class="card-header">Experiences</h5>
				<div class="accordion" id="accordionExample">
					<% @guide.experiences.each do |experience| %>
		  			<div class="card" style="border-radius: 0">
		    			<div class="card-header" id="heading<%=experience.id%>" style="border-radius: 0">
		      			<h2 class="mb-0">
		        			<button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%=experience.id%>">
		          			<%= experience.title %>
		        			</button>
		      			</h2>
		    			</div>
		    			<div id="collapse<%=experience.id%>" class="collapse" data-parent="#accordionExample">
		      			<img src="<%= experience.img %>" class="card-img-top" style="border-top-right-radius: 0;border-top-left-radius: 0;">
		      			<div class="card-body">
		        			<%= experience.description %>
		      			</div>
		    			</div>
		  			</div>
		  		<% end %>
				</div>
				<a href="/guides/<%= @user.id %>/experiences/new" class="btn btn-block btn-success" style="border-top-right-radius: 0;border-top-left-radius: 0;">Add Experience <i class="fas fa-plus"></i></a>
			</div>
		</div>
<%# reviews column %>
		<div class="col-8">
			<div class="card px-0">
		  	<h5 class="card-header">Reviews</h5>
				<div class="card-body">
					<% if @reviews.empty? %>
			  		<div class="text-center">
			  			<h4>No reviews yet</h4>
			  		</div>
			  	<% else %>
				  	<% @reviews.each do |review|%>

				  			<div class="row mt-3 border-bottom pb-3">
			  					<div class="col-4 mt-3 text-center">
			  						<small class="lead text-center text-success">
											<% review.rating.times do %>
							 					<i class="fas fa-star"></i>
											<% end %>
											<% (5-review.rating).times do %>
												<i class="far fa-star"></i>
											<% end %>
										</small>
										<p class="mt-1">By: <strong class="text-secondary"><%= review.user.name %></strong></p>
										<small class="text-muted">On <%= review.created_at.strftime("%B %-d, %Y") %></small>
									</div>
									<div class="col-8 border rounded d-flex justify-content-center align-items-center bg-light">
										<p>"<%= review.body %>"</p>
									</div>
								</div>

						<% end %>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/guides/show.html.erb
<h1 class="text-center mt-3">Name:  <%= @guide.user.name %></h1>
<div class="container">
	<div class="row">
	  <div class="col-9 pl-0">
	    <% @guide.experiences.each do |experience|%>
				<li class="list-group-item">
					<div class="row no-gutters">
				    <div class="col-md-4">
				      <img src="<%= experience.img %>" class="card-img">
				    </div>
				    <div class="col-md-8">
				      <div class="card-body">
				      	<p>
					        <h5 class="card-title">Experience: </h5>
					        <h4><%= experience.title %></h4>
					      </p>
				        <p class="card-text">Description: </p>
				        <p><%= experience.description %></p>
				      </div>
				    </div>
  				</div>
				</li>
			<% end %>
	  </div>

		<div class="col-3 border rounded pt-2">
			<div class="d-block d-sm-none">
				<% if @guide.user.avatar.attached? == false %>
					<div style="border: .5rem solid white; margin-right: 1rem; width: 7rem; height: 7rem; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url('https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-768x689.jpg')" class="ml-auto"></div>
				<% else %>
					<div style="border: .5rem solid white; margin-right: 1rem; width: 100px; height: 100px; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url('<%= url_for(@guide.user.avatar) %>')" class="ml-auto"></div>
				<% end %>
			</div>
			<div class="d-none d-sm-block">
				<% if @guide.user.avatar.attached? == false %>
					<div style="border: .5rem solid white; margin-right: 1rem; width: 15rem; height: 15rem; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url('https://dcist.com/wp-content/uploads/sites/3/2019/04/Gem2-768x689.jpg')" class="ml-auto"></div>
				<% else %>
					<div style="border: .5rem solid white; margin-right: 1rem; width: 100px; height: 100px; border-radius: 50%; background-repeat: no-repeat; background-position: center center; background-size: cover; background-image: url('<%= url_for(@guide.user.avatar) %>')" class="ml-auto"></div>
				<% end %>
			</div>
	    <h3>Bio</h3>
	    <p>
	    	<%= @guide.bio %>
	  	</p>
	    <h3>Location</h3>
	    <p>
	    	<%= @guide.user.location %>
	    </p>
			<%= link_to 'Chat', conversations_path(sender_id: current_user.id, recipient_id: @guide.user.id), method: "post", class:"text-white btn btn-success btn-block my-3"%>
		</div>

	</div>
</div>